trigger:
- develop

pool:
  name: sso  # Your self-hosted agent

stages:
- stage: Build
  displayName: 'Build and Test React App'
  jobs:
  - job: Build
    displayName: 'Install, Test & Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: |
        npm install
        npm run build
      displayName: 'Build React App'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/build'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/ssoui.zip'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/ssoui.zip'
        artifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy React App'
  dependsOn: Build  # Runs only if Build is successful
  condition: succeeded()
  jobs:
  - deployment: DeployToAzure
    displayName: 'Deploy to Azure Static Web App'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: 'AzureDevOpsConnection'
              appName: 'ssoui'
              package: "$(Pipeline.Workspace)/drop/**/*.zip"
              runtimeStack: 'NODE|18-lts'
            
          - task: AzureCLI@2
            displayName: "Set WEBSITE_RUN_FROM_PACKAGE to 0"
            inputs:
              azureSubscription: "AzureDevOpsConnection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config appsettings set --resource-group "ssoauthservice_group" --name "ssoauthservice" --settings WEBSITE_RUN_FROM_PACKAGE=0