trigger:
  - develop  # Runs pipeline on push to main branch

pool:
  name: 'sso'
  vmImage: 'ssoui'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # Use the latest stable Node.js version

  - script: |
      cd $(Build.SourcesDirectory)
      ls -la  # List files to check if build exists
      npm install
      npm run build
    displayName: 'Install Dependencies & Build React App'

  - task: ArchiveFiles@2
    displayName: 'Archive React Build Files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/react-build.zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/react-build.zip'
      artifactName: 'drop'

  - task: AzureWebApp@1
    displayName: 'Deploy React App to Azure App Service'
    inputs:
      azureSubscription: 'AzureDevOpsConnection'
      appName: 'ssoui' 
      package: '$(Pipeline.Workspace)/drop/react-build.zip'