trigger:
- develop

pool:
  name: sso 

stages:
- stage: Build
  displayName: 'Build and Test React App'
  jobs:
  - job: Build
    displayName: 'Install, Test & Build'
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '18.x'

    - script: rm -rf node_modules package-lock.json build
      displayName: 'Clean Old Files'

    - script: npm install
      displayName: 'Install Dependencies'

    - script: npm run build -- --output-path=build
      displayName: 'Build React App'
      env:
        CI: false